name: Post Video a Telegram

on:
  schedule:
    - cron: '30 9 * * *'  # 10:30 Italiana (o 11:30 con ora legale)
    - cron: '30 18 * * *' # 19:30 Italiana (o 20:30 con ora legale)
  workflow_dispatch:      # <--- QUESTO ABILITA IL TASTO MANUALE

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codice
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install google-api-python-client google-auth-httplib2 google-auth-oauthlib requests pandas openpyxl

      - name: Esegui Bot
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GDRIVE_JSON }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python bot.py
